<?php


/**
 * Skeleton subclass for representing a row from the 'sf_news_album' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 29/08/2012 15:54:50
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfLynxNewsPlugin.lib.model
 */
class SfNewsAlbum extends BaseSfNewsAlbum {

} // SfNewsAlbum
