<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sf_news_video' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 29/08/2012 15:56:31
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfLynxNewsPlugin.lib.model
 */
class SfNewsVideoPeer extends BaseSfNewsVideoPeer {
    
    public static function getVideoNews($idNews)
    {
        //Obtengo el idioma principal
        $c = new Criteria();
        //Eliminamos la columnas de seleccion en caso de que esten definidas
        $c->clearSelectColumns();
        //Se Agregan las Columnas necesarias        
        $c->addSelectColumn(self::ID_NEWS_VIDEO);
        $c->addSelectColumn(VideosPeer::TITULO_VIDEO);
        $c->addSelectColumn(VideosPeer::URL_VIDEO);
        $c->addSelectColumn(VideosPeer::ID_VIDEO);
        
        $c->addJoin(self::ID_VIDEO, VideosPeer::ID_VIDEO, Criteria::INNER_JOIN);
        //Filtros
        $c->add(self::ID_NEWS,$idNews, Criteria::EQUAL);
        $rs = self::doSelectStmt($c);
        //Se recuperan los registros y se genera arreglo
        while($res = $rs->fetch())
        {
            $dato['id_news_video'] = $res['ID_NEWS_VIDEO'];
            $dato['video'] = $res['TITULO_VIDEO'];
            $dato['url'] = $res['URL_VIDEO'];
            $dato['id_video'] = $res['ID_VIDEO'];
            $datos[] = $dato;
        }
        if (!empty($datos)){
            return $datos;
        }else{
            return false;
        }
    }
    
    public static function checkVideoNews($idNews, $id_video) {

        $c = new Criteria();
        $c->add(self::ID_NEWS,$idNews, Criteria::EQUAL);
        $c->add(self::ID_VIDEO,$id_video, Criteria::EQUAL);
        return self::doCount($c);        
    }

} // SfNewsVideoPeer
