<?php


/**
 * Skeleton subclass for representing a row from the 'sf_news' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Thu Apr 22 10:12:07 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfLynxNewsPlugin.lib.model
 */
class SfNews extends BaseSfNews {
  public function __toString()
  {
    return $this->getTitle();
  }

  public function getUrlPermalink()
	{
		$text = ucwords(strtolower(trim($this->getTitle())));
		// strip all non word chars
		$text = preg_replace('/\W/', ' ', $text);
		// replace all white space sections with a dash
		$text = preg_replace('/\ +/', '-', $text);
		// trim dashes
		$text = preg_replace('/\-$/', '', $text);
		$text = preg_replace('/^\-/', '', $text);
    $text = str_replace("[ñ]","n",$text);
    $text = str_replace("[Ñ]","N",$text);
    $text = str_replace("[ñ]","n",$text);

    $valida = new lynxValida();
    $text = $valida->limpiaCadena($text);
    $text = $valida->convierteEnUrl($text);
    
		return $this->id_news."-".$text;
	}
  
  //Sobre escrita la funcion para cambiar el formato a todo el site
  public function getDate($format = 'd-m-Y')
	{
		if ($this->date === null) {
			return null;
		}


		if ($this->date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

} // SfNews
