<?php
/**
 * Skeleton subclass for performing query and update operations on the 'sf_news' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Thu Apr 22 10:12:07 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfLynxNewsPlugin.lib.model
 */
class SfNewsPeer extends BaseSfNewsPeer {
  public static function getFilesNews($idNews)
  {
    //Obtengo el idioma principal
    $c = new Criteria();
    //Eliminamos la columnas de seleccion en caso de que esten definidas
    $c->clearSelectColumns();
    //Se Agregan las Columnas necesarias        
    $c->addSelectColumn(SfNewsArchivosPeer::ID_NEWS_ARCHIVO);
    $c->addSelectColumn(SfArchivosSeccionPeer::TITULO_ARCHIVO);
    $c->addSelectColumn(SfArchivosSeccionPeer::ARCHIVO);

    $c->addJoin(SfNewsArchivosPeer::ID_ARCHIVO, SfArchivosSeccionPeer::ID_ARCHIVO_SECCION, Criteria::INNER_JOIN);
    //Filtros
    $c->add(SfNewsArchivosPeer::ID_NEWS,$idNews, Criteria::EQUAL);
    $rs = self::doSelectStmt($c);
    //Se recuperan los registros y se genera arreglo
    while($res = $rs->fetch())
    {
      $dato['id_news_archivo'] = $res['ID_NEWS_ARCHIVO'];
      $dato['archivo'] = $res['TITULO_ARCHIVO'];
      $dato['file'] = $res['ARCHIVO'];
      $datos[] = $dato;
    }

    if (!empty($datos)){
      return $datos;
    }else{
      return false;
    }
  }

  public static function checkFileNews($idNews, $id_file) {
    $c = new Criteria();
    $c->add(SfNewsArchivosPeer::ID_NEWS,$idNews, Criteria::EQUAL);
    $c->add(SfNewsArchivosPeer::ID_ARCHIVO,$id_file, Criteria::EQUAL);
    return self::doCount($c);
  }

  public static function checkFileNoticia($idNews, $id_file) {
    $c = new Criteria();
    $c->add(SfNewsArchivosPeer::ID_NEWS,$idNews, Criteria::EQUAL);
    $c->add(SfNewsArchivosPeer::ID_ARCHIVO,$id_file, Criteria::EQUAL);
    return self::doCount($c);
  }
  
  //Devuelve las noticias ordenadas por fecha
  public static function getNoticiasRecientes($limit = 3, $categoria = "") {
    $c = new Criteria();
    $c->add(self::STATUS, 1, Criteria::EQUAL);
    if($categoria)
    {
        $c->add(self::CATEGORY, $categoria, Criteria::EQUAL);
    }
    $c->addDescendingOrderByColumn('date');
    $c->setLimit($limit);
    
    return self::doSelect($c);
  }
  
  //Devuelve las noticias ordenadas por fecha
  public static function getNoticiasRecientesHome($limit = 3) {
    $c = new Criteria();
    $c->add(self::STATUS, 1, Criteria::EQUAL);
    $c->add(self::CATEGORY, 0, Criteria::EQUAL);
    $c->add(self::IMAGE_PRINCIPAL, "", Criteria::NOT_EQUAL);
    $c->addDescendingOrderByColumn('date');
    $c->setLimit($limit);
    
    return self::doSelect($c);
  }
} // SfNewsPeer
