<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sf_news_archivos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 29/08/2012 15:58:44
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfLynxNewsPlugin.lib.model
 */
class SfNewsArchivosPeer extends BaseSfNewsArchivosPeer {
    
    public static function getFilesNews($idNews)
    {
        //Obtengo el idioma principal
        $c = new Criteria();
        //Eliminamos la columnas de seleccion en caso de que esten definidas
        $c->clearSelectColumns();
        //Se Agregan las Columnas necesarias        
        $c->addSelectColumn(self::ID_NEWS_ARCHIVO);
        $c->addSelectColumn(SfArchivosSeccionPeer::TITULO_ARCHIVO);
        $c->addSelectColumn(SfArchivosSeccionPeer::ARCHIVO);
        
        $c->addJoin(self::ID_ARCHIVO, SfArchivosSeccionPeer::ID_ARCHIVO_SECCION, Criteria::INNER_JOIN);
        //Filtros
        $c->add(self::ID_NEWS,$idNews, Criteria::EQUAL);
        $rs = self::doSelectStmt($c);
        //Se recuperan los registros y se genera arreglo
        while($res = $rs->fetch())
        {
            $dato['id_news_archivo'] = $res['ID_NEWS_ARCHIVO'];
            $dato['archivo'] = $res['TITULO_ARCHIVO'];
            $dato['file'] = $res['ARCHIVO'];
            $datos[] = $dato;
        }
        if (!empty($datos)){
            return $datos;
        }else{
            return false;
        }
    }
    
    public static function checkFileNews($idNews, $id_file) {

        $c = new Criteria();
        $c->add(self::ID_NEWS,$idNews, Criteria::EQUAL);
        $c->add(self::ID_ARCHIVO,$id_file, Criteria::EQUAL);
        return self::doCount($c);
        
    }
    public static function checkFileNoticia($idNews, $id_file) {

        $c = new Criteria();
        $c->add(self::ID_NEWS,$idNews, Criteria::EQUAL);
        $c->add(self::ID_ARCHIVO,$id_file, Criteria::EQUAL);
        return self::doCount($c);
        
    }

} // SfNewsArchivosPeer
