<?php

/**
 * Base class that represents a row from the 'sf_news' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 09/08/2013 16:18:23
 *
 * @package    plugins.sfLynxNewsPlugin.lib.model.om
 */
abstract class BaseSfNews extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        SfNewsPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_news field.
	 * @var        int
	 */
	protected $id_news;

	/**
	 * The value for the id_profile field.
	 * @var        int
	 */
	protected $id_profile;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the sub_title field.
	 * @var        string
	 */
	protected $sub_title;

	/**
	 * The value for the body field.
	 * @var        string
	 */
	protected $body;

	/**
	 * The value for the date field.
	 * @var        string
	 */
	protected $date;

	/**
	 * The value for the summary field.
	 * @var        string
	 */
	protected $summary;

	/**
	 * The value for the author field.
	 * @var        string
	 */
	protected $author;

	/**
	 * The value for the image_principal field.
	 * @var        string
	 */
	protected $image_principal;

	/**
	 * The value for the image field.
	 * @var        string
	 */
	protected $image;

	/**
	 * The value for the status field.
	 * @var        string
	 */
	protected $status;

	/**
	 * The value for the home field.
	 * @var        string
	 */
	protected $home;

	/**
	 * The value for the permalink field.
	 * @var        string
	 */
	protected $permalink;

	/**
	 * The value for the home_title field.
	 * @var        string
	 */
	protected $home_title;

	/**
	 * The value for the category field.
	 * @var        string
	 */
	protected $category;

	/**
	 * The value for the sticky field.
	 * Note: this column has a database default value of: '0'
	 * @var        string
	 */
	protected $sticky;

	/**
	 * @var        array SfNewsAccess[] Collection to store aggregation of SfNewsAccess objects.
	 */
	protected $collSfNewsAccesss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSfNewsAccesss.
	 */
	private $lastSfNewsAccessCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'SfNewsPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->sticky = '0';
	}

	/**
	 * Initializes internal state of BaseSfNews object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id_news] column value.
	 * 
	 * @return     int
	 */
	public function getIdNews()
	{
		return $this->id_news;
	}

	/**
	 * Get the [id_profile] column value.
	 * 
	 * @return     int
	 */
	public function getIdProfile()
	{
		return $this->id_profile;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [sub_title] column value.
	 * 
	 * @return     string
	 */
	public function getSubTitle()
	{
		return $this->sub_title;
	}

	/**
	 * Get the [body] column value.
	 * 
	 * @return     string
	 */
	public function getBody()
	{
		return $this->body;
	}

	/**
	 * Get the [optionally formatted] temporal [date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDate($format = 'Y-m-d')
	{
		if ($this->date === null) {
			return null;
		}


		if ($this->date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [summary] column value.
	 * 
	 * @return     string
	 */
	public function getSummary()
	{
		return $this->summary;
	}

	/**
	 * Get the [author] column value.
	 * 
	 * @return     string
	 */
	public function getAuthor()
	{
		return $this->author;
	}

	/**
	 * Get the [image_principal] column value.
	 * 
	 * @return     string
	 */
	public function getImagePrincipal()
	{
		return $this->image_principal;
	}

	/**
	 * Get the [image] column value.
	 * 
	 * @return     string
	 */
	public function getImage()
	{
		return $this->image;
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     string
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [home] column value.
	 * 
	 * @return     string
	 */
	public function getHome()
	{
		return $this->home;
	}

	/**
	 * Get the [permalink] column value.
	 * 
	 * @return     string
	 */
	public function getPermalink()
	{
		return $this->permalink;
	}

	/**
	 * Get the [home_title] column value.
	 * 
	 * @return     string
	 */
	public function getHomeTitle()
	{
		return $this->home_title;
	}

	/**
	 * Get the [category] column value.
	 * 
	 * @return     string
	 */
	public function getCategory()
	{
		return $this->category;
	}

	/**
	 * Get the [sticky] column value.
	 * 
	 * @return     string
	 */
	public function getSticky()
	{
		return $this->sticky;
	}

	/**
	 * Set the value of [id_news] column.
	 * 
	 * @param      int $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setIdNews($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_news !== $v) {
			$this->id_news = $v;
			$this->modifiedColumns[] = SfNewsPeer::ID_NEWS;
		}

		return $this;
	} // setIdNews()

	/**
	 * Set the value of [id_profile] column.
	 * 
	 * @param      int $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setIdProfile($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_profile !== $v) {
			$this->id_profile = $v;
			$this->modifiedColumns[] = SfNewsPeer::ID_PROFILE;
		}

		return $this;
	} // setIdProfile()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = SfNewsPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [sub_title] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setSubTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->sub_title !== $v) {
			$this->sub_title = $v;
			$this->modifiedColumns[] = SfNewsPeer::SUB_TITLE;
		}

		return $this;
	} // setSubTitle()

	/**
	 * Set the value of [body] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setBody($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->body !== $v) {
			$this->body = $v;
			$this->modifiedColumns[] = SfNewsPeer::BODY;
		}

		return $this;
	} // setBody()

	/**
	 * Sets the value of [date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date !== null && $tmpDt = new DateTime($this->date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = SfNewsPeer::DATE;
			}
		} // if either are not null

		return $this;
	} // setDate()

	/**
	 * Set the value of [summary] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setSummary($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->summary !== $v) {
			$this->summary = $v;
			$this->modifiedColumns[] = SfNewsPeer::SUMMARY;
		}

		return $this;
	} // setSummary()

	/**
	 * Set the value of [author] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setAuthor($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->author !== $v) {
			$this->author = $v;
			$this->modifiedColumns[] = SfNewsPeer::AUTHOR;
		}

		return $this;
	} // setAuthor()

	/**
	 * Set the value of [image_principal] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setImagePrincipal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image_principal !== $v) {
			$this->image_principal = $v;
			$this->modifiedColumns[] = SfNewsPeer::IMAGE_PRINCIPAL;
		}

		return $this;
	} // setImagePrincipal()

	/**
	 * Set the value of [image] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setImage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image !== $v) {
			$this->image = $v;
			$this->modifiedColumns[] = SfNewsPeer::IMAGE;
		}

		return $this;
	} // setImage()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->status !== $v) {
			$this->status = $v;
			$this->modifiedColumns[] = SfNewsPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Set the value of [home] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setHome($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->home !== $v) {
			$this->home = $v;
			$this->modifiedColumns[] = SfNewsPeer::HOME;
		}

		return $this;
	} // setHome()

	/**
	 * Set the value of [permalink] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setPermalink($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->permalink !== $v) {
			$this->permalink = $v;
			$this->modifiedColumns[] = SfNewsPeer::PERMALINK;
		}

		return $this;
	} // setPermalink()

	/**
	 * Set the value of [home_title] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setHomeTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->home_title !== $v) {
			$this->home_title = $v;
			$this->modifiedColumns[] = SfNewsPeer::HOME_TITLE;
		}

		return $this;
	} // setHomeTitle()

	/**
	 * Set the value of [category] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setCategory($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->category !== $v) {
			$this->category = $v;
			$this->modifiedColumns[] = SfNewsPeer::CATEGORY;
		}

		return $this;
	} // setCategory()

	/**
	 * Set the value of [sticky] column.
	 * 
	 * @param      string $v new value
	 * @return     SfNews The current object (for fluent API support)
	 */
	public function setSticky($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->sticky !== $v || $this->isNew()) {
			$this->sticky = $v;
			$this->modifiedColumns[] = SfNewsPeer::STICKY;
		}

		return $this;
	} // setSticky()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->sticky !== '0') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_news = (isset($row[$startcol + 0]) && $row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_profile = (isset($row[$startcol + 1]) && $row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->title = (isset($row[$startcol + 2]) && $row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->sub_title = (isset($row[$startcol + 3]) && $row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->body = (isset($row[$startcol + 4]) && $row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->date = (isset($row[$startcol + 5]) && $row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->summary = (isset($row[$startcol + 6]) && $row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->author = (isset($row[$startcol + 7]) && $row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->image_principal = (isset($row[$startcol + 8]) && $row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->image = (isset($row[$startcol + 9]) && $row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->status = (isset($row[$startcol + 10]) && $row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->home = (isset($row[$startcol + 11]) && $row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->permalink = (isset($row[$startcol + 12]) && $row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->home_title = (isset($row[$startcol + 13]) && $row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->category = (isset($row[$startcol + 14]) && $row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->sticky = (isset($row[$startcol + 15]) && $row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 16; // 16 = SfNewsPeer::NUM_COLUMNS - SfNewsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating SfNews object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SfNewsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = SfNewsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collSfNewsAccesss = null;
			$this->lastSfNewsAccessCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SfNewsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSfNews:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				SfNewsPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSfNews:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SfNewsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSfNews:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSfNews:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				SfNewsPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = SfNewsPeer::ID_NEWS;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = SfNewsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdNews($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += SfNewsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collSfNewsAccesss !== null) {
				foreach ($this->collSfNewsAccesss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = SfNewsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collSfNewsAccesss !== null) {
					foreach ($this->collSfNewsAccesss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SfNewsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdNews();
				break;
			case 1:
				return $this->getIdProfile();
				break;
			case 2:
				return $this->getTitle();
				break;
			case 3:
				return $this->getSubTitle();
				break;
			case 4:
				return $this->getBody();
				break;
			case 5:
				return $this->getDate();
				break;
			case 6:
				return $this->getSummary();
				break;
			case 7:
				return $this->getAuthor();
				break;
			case 8:
				return $this->getImagePrincipal();
				break;
			case 9:
				return $this->getImage();
				break;
			case 10:
				return $this->getStatus();
				break;
			case 11:
				return $this->getHome();
				break;
			case 12:
				return $this->getPermalink();
				break;
			case 13:
				return $this->getHomeTitle();
				break;
			case 14:
				return $this->getCategory();
				break;
			case 15:
				return $this->getSticky();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = SfNewsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdNews(),
			$keys[1] => $this->getIdProfile(),
			$keys[2] => $this->getTitle(),
			$keys[3] => $this->getSubTitle(),
			$keys[4] => $this->getBody(),
			$keys[5] => $this->getDate(),
			$keys[6] => $this->getSummary(),
			$keys[7] => $this->getAuthor(),
			$keys[8] => $this->getImagePrincipal(),
			$keys[9] => $this->getImage(),
			$keys[10] => $this->getStatus(),
			$keys[11] => $this->getHome(),
			$keys[12] => $this->getPermalink(),
			$keys[13] => $this->getHomeTitle(),
			$keys[14] => $this->getCategory(),
			$keys[15] => $this->getSticky(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SfNewsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdNews($value);
				break;
			case 1:
				$this->setIdProfile($value);
				break;
			case 2:
				$this->setTitle($value);
				break;
			case 3:
				$this->setSubTitle($value);
				break;
			case 4:
				$this->setBody($value);
				break;
			case 5:
				$this->setDate($value);
				break;
			case 6:
				$this->setSummary($value);
				break;
			case 7:
				$this->setAuthor($value);
				break;
			case 8:
				$this->setImagePrincipal($value);
				break;
			case 9:
				$this->setImage($value);
				break;
			case 10:
				$this->setStatus($value);
				break;
			case 11:
				$this->setHome($value);
				break;
			case 12:
				$this->setPermalink($value);
				break;
			case 13:
				$this->setHomeTitle($value);
				break;
			case 14:
				$this->setCategory($value);
				break;
			case 15:
				$this->setSticky($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = SfNewsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdNews($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdProfile($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTitle($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setSubTitle($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setBody($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDate($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setSummary($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setAuthor($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setImagePrincipal($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setImage($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setStatus($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setHome($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setPermalink($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setHomeTitle($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setCategory($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setSticky($arr[$keys[15]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(SfNewsPeer::DATABASE_NAME);

		if ($this->isColumnModified(SfNewsPeer::ID_NEWS)) $criteria->add(SfNewsPeer::ID_NEWS, $this->id_news);
		if ($this->isColumnModified(SfNewsPeer::ID_PROFILE)) $criteria->add(SfNewsPeer::ID_PROFILE, $this->id_profile);
		if ($this->isColumnModified(SfNewsPeer::TITLE)) $criteria->add(SfNewsPeer::TITLE, $this->title);
		if ($this->isColumnModified(SfNewsPeer::SUB_TITLE)) $criteria->add(SfNewsPeer::SUB_TITLE, $this->sub_title);
		if ($this->isColumnModified(SfNewsPeer::BODY)) $criteria->add(SfNewsPeer::BODY, $this->body);
		if ($this->isColumnModified(SfNewsPeer::DATE)) $criteria->add(SfNewsPeer::DATE, $this->date);
		if ($this->isColumnModified(SfNewsPeer::SUMMARY)) $criteria->add(SfNewsPeer::SUMMARY, $this->summary);
		if ($this->isColumnModified(SfNewsPeer::AUTHOR)) $criteria->add(SfNewsPeer::AUTHOR, $this->author);
		if ($this->isColumnModified(SfNewsPeer::IMAGE_PRINCIPAL)) $criteria->add(SfNewsPeer::IMAGE_PRINCIPAL, $this->image_principal);
		if ($this->isColumnModified(SfNewsPeer::IMAGE)) $criteria->add(SfNewsPeer::IMAGE, $this->image);
		if ($this->isColumnModified(SfNewsPeer::STATUS)) $criteria->add(SfNewsPeer::STATUS, $this->status);
		if ($this->isColumnModified(SfNewsPeer::HOME)) $criteria->add(SfNewsPeer::HOME, $this->home);
		if ($this->isColumnModified(SfNewsPeer::PERMALINK)) $criteria->add(SfNewsPeer::PERMALINK, $this->permalink);
		if ($this->isColumnModified(SfNewsPeer::HOME_TITLE)) $criteria->add(SfNewsPeer::HOME_TITLE, $this->home_title);
		if ($this->isColumnModified(SfNewsPeer::CATEGORY)) $criteria->add(SfNewsPeer::CATEGORY, $this->category);
		if ($this->isColumnModified(SfNewsPeer::STICKY)) $criteria->add(SfNewsPeer::STICKY, $this->sticky);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(SfNewsPeer::DATABASE_NAME);

		$criteria->add(SfNewsPeer::ID_NEWS, $this->id_news);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdNews();
	}

	/**
	 * Generic method to set the primary key (id_news column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdNews($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of SfNews (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdProfile($this->id_profile);

		$copyObj->setTitle($this->title);

		$copyObj->setSubTitle($this->sub_title);

		$copyObj->setBody($this->body);

		$copyObj->setDate($this->date);

		$copyObj->setSummary($this->summary);

		$copyObj->setAuthor($this->author);

		$copyObj->setImagePrincipal($this->image_principal);

		$copyObj->setImage($this->image);

		$copyObj->setStatus($this->status);

		$copyObj->setHome($this->home);

		$copyObj->setPermalink($this->permalink);

		$copyObj->setHomeTitle($this->home_title);

		$copyObj->setCategory($this->category);

		$copyObj->setSticky($this->sticky);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getSfNewsAccesss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSfNewsAccess($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdNews(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     SfNews Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     SfNewsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new SfNewsPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collSfNewsAccesss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSfNewsAccesss()
	 */
	public function clearSfNewsAccesss()
	{
		$this->collSfNewsAccesss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSfNewsAccesss collection (array).
	 *
	 * By default this just sets the collSfNewsAccesss collection to an empty array (like clearcollSfNewsAccesss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSfNewsAccesss()
	{
		$this->collSfNewsAccesss = array();
	}

	/**
	 * Gets an array of SfNewsAccess objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SfNews has previously been saved, it will retrieve
	 * related SfNewsAccesss from storage. If this SfNews is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SfNewsAccess[]
	 * @throws     PropelException
	 */
	public function getSfNewsAccesss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SfNewsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSfNewsAccesss === null) {
			if ($this->isNew()) {
			   $this->collSfNewsAccesss = array();
			} else {

				$criteria->add(SfNewsAccessPeer::ID_NEWS, $this->id_news);

				SfNewsAccessPeer::addSelectColumns($criteria);
				$this->collSfNewsAccesss = SfNewsAccessPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SfNewsAccessPeer::ID_NEWS, $this->id_news);

				SfNewsAccessPeer::addSelectColumns($criteria);
				if (!isset($this->lastSfNewsAccessCriteria) || !$this->lastSfNewsAccessCriteria->equals($criteria)) {
					$this->collSfNewsAccesss = SfNewsAccessPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSfNewsAccessCriteria = $criteria;
		return $this->collSfNewsAccesss;
	}

	/**
	 * Returns the number of related SfNewsAccess objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SfNewsAccess objects.
	 * @throws     PropelException
	 */
	public function countSfNewsAccesss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SfNewsPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSfNewsAccesss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SfNewsAccessPeer::ID_NEWS, $this->id_news);

				$count = SfNewsAccessPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SfNewsAccessPeer::ID_NEWS, $this->id_news);

				if (!isset($this->lastSfNewsAccessCriteria) || !$this->lastSfNewsAccessCriteria->equals($criteria)) {
					$count = SfNewsAccessPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSfNewsAccesss);
				}
			} else {
				$count = count($this->collSfNewsAccesss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SfNewsAccess object to this object
	 * through the SfNewsAccess foreign key attribute.
	 *
	 * @param      SfNewsAccess $l SfNewsAccess
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSfNewsAccess(SfNewsAccess $l)
	{
		if ($this->collSfNewsAccesss === null) {
			$this->initSfNewsAccesss();
		}
		if (!in_array($l, $this->collSfNewsAccesss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSfNewsAccesss, $l);
			$l->setSfNews($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SfNews is new, it will return
	 * an empty collection; or if this SfNews has previously
	 * been saved, it will retrieve related SfNewsAccesss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SfNews.
	 */
	public function getSfNewsAccesssJoinLxProfile($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SfNewsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSfNewsAccesss === null) {
			if ($this->isNew()) {
				$this->collSfNewsAccesss = array();
			} else {

				$criteria->add(SfNewsAccessPeer::ID_NEWS, $this->id_news);

				$this->collSfNewsAccesss = SfNewsAccessPeer::doSelectJoinLxProfile($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SfNewsAccessPeer::ID_NEWS, $this->id_news);

			if (!isset($this->lastSfNewsAccessCriteria) || !$this->lastSfNewsAccessCriteria->equals($criteria)) {
				$this->collSfNewsAccesss = SfNewsAccessPeer::doSelectJoinLxProfile($criteria, $con, $join_behavior);
			}
		}
		$this->lastSfNewsAccessCriteria = $criteria;

		return $this->collSfNewsAccesss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collSfNewsAccesss) {
				foreach ((array) $this->collSfNewsAccesss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collSfNewsAccesss = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseSfNews:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseSfNews::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseSfNews
