<?php


/**
 * This class defines the structure of the 'sf_language' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 09/08/2013 16:18:23
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfLynxLanguagePlugin.lib.model.map
 */
class SfLanguageTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfLynxLanguagePlugin.lib.model.map.SfLanguageTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sf_language');
		$this->setPhpName('SfLanguage');
		$this->setClassname('SfLanguage');
		$this->setPackage('plugins.sfLynxLanguagePlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_LANGUAGE', 'IdLanguage', 'INTEGER', true, 11, null);
		$this->addColumn('LANGUAGE', 'Language', 'VARCHAR', false, 10, null);
		$this->addColumn('COUNTRY', 'Country', 'VARCHAR', false, 10, null);
		$this->addColumn('LANG_COUNTRY', 'LangCountry', 'VARCHAR', true, 10, null);
		$this->addColumn('PRINCIPAL', 'Principal', 'CHAR', false, null, '0');
		$this->addColumn('STATUS', 'Status', 'CHAR', false, null, '0');
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SfLanguageTableMap
